services:
  witness:
    image: gcr.io/trillian-opensource-ci/omniwitness:${WITNESS_VERSION}
    volumes:
        - type: volume
          source: data
          target: /data
          volume:
            nocopy: true
        - type: bind
          source: ${WITNESS_PRIVATE_KEY_PATH}
          target: /private_key
          read_only: true
    command:
      - "--listen=:8100"
      - "--db_file=/data/witness.sqlite"
      - "--private_key_path=/private_key"
      - "--logtostderr"
      - "--v=2"
    restart: always
    ports:
      - "8100:8100"
volumes:
  data:
